### ISSUE TITLE
Migrate content type

### ISSUE THREAD

**Issue by Guite** [zikula-modules/Formicula#79]
The content type needs to be updated for Content 5.
This raises core requirement to 2.0.11+.

**Comment by robbrandt** [comment]
I think I have run into this as a bug.  Upon uploading the module and going to , I get 500 Internal Server Error, and apache log says:

PHP Fatal error:  Class 'Content_AbstractContentType' not found in /home/sitename/public_html/modules/zikula/Formicula/ContentType/Form.php on line 31, referer: http://transformingvillages.org/blocks/admin/view

When I go to /extensions/module/list and try to install it.

I installed from master as it appears there's been a ton of commits since the last release 18 months ago.

**Comment by Guite** [comment]
As a workaround delete the `ContentType` directory and https://github.com/zikula-modules/Formicula/blob/master/ZikulaFormiculaModule.php#L24-L27

**Comment by Guite** [comment]
Going to look at this, but may need a few days.
